<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' target='_blank'><img src='{@me['litpic']}'/></a>\"); ",178,332);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",417,432);
$z[1][4]=array();
$z[2]=Array("title","",448,462);
$z[2][4]=array();
$z[3]=Array("description","",486,506);
$z[3][4]=array();
$z[4]=Array("click","",601,615);
$z[4][4]=array();
$z[5]=Array("scores","",660,675);
$z[5][4]=array();

?>