<div class="layui-col-xs12 layui-col-sm4 layui-col-md4">
            <div class="item">
              <img src="[field:litpic/]">
              <div class="cont-text">
                <div class="data">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</div>
                <p class="address"><span>[field:title/]</span></p>
                <p class="briefly"><i class="layui-icon layui-icon-user"></i>[field:writer /]</p>
                
              </div>
            </div>
          </div>