<?php
$z[0]=Array("global","",272,304);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",379,411);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",914,946);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channel","\r\n          <a href=\"[field:typeurl/]\"  class=\"active\">[field:typename/]</a>\r\n          ",1168,1304);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['row']="1";
$z[4]=Array("arclist","\r\n          <div class=\"layui-col-xs12 layui-col-sm4 layui-col-md4\">\r\n            <div class=\"item\">\r\n              <div style=\"overflow:hidden;height:225px;width:100%\">\r\n                <div style=\"vertical-align:middle;\">\r\n                  <img src=\"[field:litpic/]\">\r\n                </div>              \r\n              </div>\r\n              <div class=\"cont-text\">\r\n                <div class=\"data\">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</div>\r\n                <p class=\"address\"><span>[field:title/]</span></p>\r\n                <p class=\"briefly\"><i class=\"layui-icon layui-icon-user\"></i>[field:writer /]</p>\r\n                \r\n              </div>\r\n            </div>\r\n          </div>\r\n          ",2098,2879);
$z[4][4]=array();
$z[4][4]['titlelen']="60";
$z[4][4]['row']="15";
$z[4][4]['typeid']="1";
$z[5]=Array("include","",2968,3011);
$z[5][4]=array();
$z[5][4]['filename']="html/footer.html";
$z[6]=Array("global","",3053,3085);
$z[6][4]=array();
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",3184,3216);
$z[7][4]=array();
$z[7][4]['name']="cfg_templets_skin";

?>