<div class="layui-col-xs12 layui-col-sm4 layui-col-md4">
            <div class="item">
              <div style="overflow:hidden;height:225px;width:100%">
                <div style="vertical-align:middle;">
                  <img src="[field:litpic/]">
                </div>              
              </div>
              <div class="cont-text">
                <div class="data">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</div>
                <p class="address"><span>[field:title/]</span></p>
                <p class="briefly"><i class="layui-icon layui-icon-user"></i>[field:writer /]</p>
                
              </div>
            </div>
          </div>